spring:
    application:
        name: javava-pay
    profiles:
        active: prod
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.200.229:3306/test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf8
        username: root
        password: iaFaI8ZdB%#s
    jpa:
        open-in-view: true
        show-sql: true
        hibernate:
          ddl-auto: update
server:
    servlet:
        context-path: /javavapay
    port: 80
    ip: 127.0.0.1