spring:
    thymeleaf:
        cache: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.150.129:3306/javava?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: develop
            connection-init-sqls: set names utf8mb4
    mail:
        host: smtp.exmail.qq.com
        port: 465
        username: debug@javava.cn
        password: 123456
        protocol: smtp
        properties:
            mail:
                debug: false
                smtp:
                    auth: true
                    ssl:
                        enable: true
weixin:
    api:
        shortUrl: https://api.mch.weixin.qq.com/tools/shorturl
        report: https://api.mch.weixin.qq.com/payitil/report
        app-id: wxfe19480979014ade
        mch-id: 1461351402
        key: ouQ1s6moJu70mJJx7LuU82gbWaIR4s5D
        signType: MD5
        httpConnectTimeout: 6000
        httpReadTimeout: 8000
javava:
    notification:
        email: zhuzhiou@qq.com