spring:
    thymeleaf:
        cache: false
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.200.229:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: iaFaI8ZdB%#s
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
    mail:
        host: smtp.exmail.qq.com
        port: 465
        username: debug@javava.cn
        password: 123456
        protocol: smtp
        properties:
            mail:
                debug: false
                smtp:
                    auth: true
                    ssl:
                        enable: true
server:
    port: 8080
    context-path: /zhifu
wx:
    api:
        unifiedOrderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
        goodsBody: 测试商品描述..
        tradeType: JSAPI #MWEB #NATIVE
        appId: wxfe19480979014ade
        mchId: 1461351402
        key: ouQ1s6moJu70mJJx7LuU82gbWaIR4s5D
        notifyUrl: http://zhifu.javava.cn/zhifu/qrcodepaySuccess
        signType: MD5
        httpConnectTimeout: 6000
        httpReadTimeout: 8000
        ip: 127.0.0.1
        shortUrl: https://api.mch.weixin.qq.com/tools/shorturl
        report: https://api.mch.weixin.qq.com/payitil/report
javava:
    notification:
        email: zhuzhiou@qq.com