spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.200.229:3306/test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf8
        username: root
        password: iaFaI8ZdB%#s
server:
    context-path: /wxpay
    port: 8088
wx:
    api:
        shortUrl: https://api.mch.weixin.qq.com/tools/shorturl
        report: https://api.mch.weixin.qq.com/payitil/report
        app-id: wxfe19480979014ade
        mch-id: 1461351402
        key: ouQ1s6moJu70mJJx7LuU82gbWaIR4s5D
        signType: MD5
        httpConnectTimeout: 6000
        httpReadTimeout: 8000