spring:
    application:
        name: pay-services
    profiles:
        active: prod
    cloud:
        inetutils:
            ignored-interfaces:
                - Microsoft.*
                - Software.*
                - VMware.*
server:
    port: 8006
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8000/eureka/
    instance:
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 10