spring:
    dubbo:
        application:
            name: users-consumer
        registry:
            address: zookeeper://192.168.160.129:2181
        protocol:
            name: dubbo
            port: 20880
    redis:
        host: 192.168.160.129
        port: 6379
        database: 0
server:
    servlet:
        context-path: /token
    port: 8080
weixin:
    api:
        appId: wx3c9fe7990504ee43
        appSecret: 86a03cf6061df50185eb49dfaf31cc59
    authz:
        redirect_uri: http://piggy.s1.natapp.cc/token/authz
javava:
    jwt:
        secret: JErH9l4oxxvsS6ktynDx0yB0IG6nhrXzAR7SSDkU53NPTrm8SoziOQOmUTCa46o0EpTfE3uODClWHGbRmfQd2g==