spring:
    application:
        name: api-gateway
server:
    port: 8090
zuul:
    ignored-services: '*'
    prefix: /api
    routes:
        live:
            path: /lives/**
            serviceId: live-services
            stripPrefix: false
        user:
            path: /users/**
            serviceId: user-services
            stripPrefix: false
        pay:
            path: /pay/**
            serviceId: pay-services
            stripPrefix: false
#security:
#    basic:
#        enabled: false
#        authorize-mode: none
#    oauth2:
#      authorization:
#        check-token-access: false
#security:
#    oauth2:
#        client:
#            client-id: f
#            client-secret: f
#            grant-type:
#        authorization:
#            realm: test
eureka:
    client:
        service-url:
            defaultZone: http://asrock:8091/eureka/