spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.150.129:3306/javava?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: develop
    jpa:
        show-sql: false
    mail:
        host: smtp.exmail.qq.com
        port: 465
        username: debug@javava.cn
        password: Zizhu20180102
        protocol: smtp
        properties:
            mail:
                debug: false
                smtp:
                    auth: true
                    ssl:
                        enable: true
zego:
    api:
        secret: 4a0af0daafe22ed2a7bd5661e87890aa
server:
    servlet:
        context-path: /zego-api
javava:
    notification:
        consignee: zhuzhiou@qq.com