spring:
    dubbo:
        application:
            name: live-consumer
        registry:
            address: zookeeper://192.168.150.129:2181
        protocol:
            name: dubbo
            port: 20880
    mail:
        host: smtp.exmail.qq.com
        port: 465
        username: debug@javava.cn
        password: Zizhu20180102
        protocol: smtp
        properties:
            mail:
                debug: false
                smtp:
                    auth: true
                    ssl:
                        enable: true
zego:
    api:
        secret: 4a0af0daafe22ed2a7bd5661e87890aa
server:
    servlet:
        context-path: /zego-api
javava:
    notification:
        consignee: zhuzhiou@qq.com