spring:
    application:
        name: api-gateway
    profiles:
        active: prod
server:
    port: 8082
zuul:
    ignored-services: '*'
    routes:
        room:
            path: /rooms/**
            serviceId: live-services
            stripPrefix: false
        stream:
            path: /streams/**
            serviceId: live-services
            stripPrefix: false
        user:
            path: /users/**
            serviceId: user-services
            stripPrefix: false
        pay:
            path: /trades/**
            serviceId: pay-services
            stripPrefix: false