spring:
    application:
        name: api-gateway
server:
    port: 8086
zuul:
    ignored-services: '*'
    routes:
        room:
            path: /rooms/**
            serviceId: live-services
            stripPrefix: false
        stream:
            path: /streams/**
            serviceId: live-services
            stripPrefix: false
        user:
            path: /users/**
            serviceId: user-services
            stripPrefix: false
        pay:
            path: /pay/**
            serviceId: pay-services
            stripPrefix: false
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8000/eureka/