spring:
    application:
        name: api-gateway
server:
    port: 8080
zuul:
    routes:
        live:
            path: /api/lives/**
            url: http://localhost:8084/lives/
#            service-id: LIVE-SERVICES