spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.150.129:3306/javava?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: develop
    mail:
        host: smtp.exmail.qq.com
        port: 465
        username: debug@javava.cn
        password: 123456
        protocol: smtp
        properties:
            mail:
                debug: false
                smtp:
                    auth: true
                    ssl:
                        enable: true
zego:
    api:
        secret: 123456
javava:
    notification:
        consignees: test@javava.cn