spring:
    application:
        name: zuul-gateway
server:
    port: 8001
zuul:
    ignored-services: '*'
    routes:
        live:
            path: /lives/**
            serviceId: live-services
            stripPrefix: false
        user:
            path: /users/**
            serviceId: user-services
            stripPrefix: false
        pay:
            path: /pay/**
            serviceId: pay-services
            stripPrefix: false
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8000/eureka/